name: Build and Test

on:
  push:
  pull_request:
    branches: [ master ]

env:
  MAKEFLAGS: -j8

jobs:

  check:
    strategy:
      matrix:
        features:
        - --enable-debug
        - --enable-debug --enable-aac --enable-msbc
        - --enable-debug --enable-mp3lame --enable-mpg123
        - --enable-faststream --enable-mp3lame
        - --enable-aplay --enable-ofono --enable-upower
        - --enable-cli --enable-rfcomm --enable-manpages
      fail-fast: false
    runs-on: ubuntu-20.04
    steps:
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install --yes --quiet --no-install-recommends \
          check \
          libasound2-dev \
          libbluetooth-dev \
          libdbus-1-dev \
          libfdk-aac-dev \
          libglib2.0-dev \
          libmp3lame-dev \
          libmpg123-dev \
          libreadline-dev \
          libsbc-dev \
          libspandsp-dev \
          python-docutils
    - uses: actions/checkout@v3
    - name: Create Build Environment
      run: |
        mkdir -p ${{ github.workspace }}/{build,m4}
        autoreconf --install
    - name: Configure GNU Automake
      working-directory: ${{ github.workspace }}/build
      run: |
        ${{ github.workspace }}/configure \
          ${{ matrix.features }} \
          --enable-test
    - name: Build
      working-directory: ${{ github.workspace }}/build
      run: make check CFLAGS="-Wall -Wextra -Werror" TESTS=
    - name: Run Tests
      working-directory: ${{ github.workspace }}/build/test
      run: make check-TESTS
    - name: Upload Tests Log
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: ${{ github.job }} (${{ matrix.features }}) logs
        path: ${{ github.workspace }}/build/test/*.log

  sanitize:
    strategy:
      matrix:
        sanitize:
        - address alignment bool bounds nonnull-attribute shift undefined
      fail-fast: false
    runs-on: ubuntu-20.04
    steps:
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install --yes --quiet --no-install-recommends \
          check \
          libasound2-dev \
          libbluetooth-dev \
          libdbus-1-dev \
          libfdk-aac-dev \
          libglib2.0-dev \
          libmp3lame-dev \
          libmpg123-dev \
          libsbc-dev \
          libspandsp-dev
    - uses: actions/checkout@v3
    - name: Create Build Environment
      run: |
        mkdir -p ${{ github.workspace }}/{build,m4}
        autoreconf --install
    - name: Configure GNU Automake
      working-directory: ${{ github.workspace }}/build
      run: |
        ${{ github.workspace }}/configure \
          --enable-aac \
          --enable-faststream \
          --enable-mp3lame \
          --enable-mpg123 \
          --enable-msbc \
          --enable-ofono \
          --enable-upower \
          --enable-aplay \
          --enable-cli \
          --enable-test
    - name: Build
      working-directory: ${{ github.workspace }}/build
      run: |
        make clean
        SANITIZERS=$(for x in ${{ matrix.sanitize }}; do echo -n " -fsanitize=$x"; done)
        make check CFLAGS="-g -O2 $SANITIZERS -fno-sanitize-recover=all" TESTS=
    - name: Run Tests
      working-directory: ${{ github.workspace }}/build/test
      env:
        CK_DEFAULT_TIMEOUT: 15
        LD_PRELOAD_SANITIZER: libasan.so.5
      run: make check-TESTS
    - name: Upload Tests Log
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: ${{ github.job }} (${{ matrix.sanitize }}) logs
        path: ${{ github.workspace }}/build/test/*.log
